# Generated by Django 4.2 on 2024-04-22 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gare",
            fields=[
                (
                    "nom",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Passager",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=30)),
                ("prenom", models.CharField(max_length=30)),
                ("dateDeNaissance", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Trajet",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("DHDepart", models.DateTimeField()),
                ("DHArrivee", models.DateTimeField()),
                (
                    "gareArrivee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrivantA",
                        to="booking.gare",
                    ),
                ),
                (
                    "gareDepart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partantDe",
                        to="booking.gare",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=30)),
                ("nom", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("addresse", models.CharField(max_length=100)),
                ("telephone", models.BigIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
