# Generated by Django 4.2 on 2024-04-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("dateResa", models.DateField(auto_now=True)),
                ("numeroResa", models.IntegerField(primary_key=True, serialize=False)),
                ("numeroPlace", models.IntegerField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booking.client"
                    ),
                ),
                (
                    "trajet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booking.trajet"
                    ),
                ),
            ],
        ),
    ]
