# Generated by Django 4.2 on 2024-04-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="passager",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.passager",
            ),
            preserve_default=False,
        ),
    ]
