# Generated by Django 4.2 on 2024-04-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_reservation_passager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="numeroResa",
            field=models.IntegerField(
                default=59245625, primary_key=True, serialize=False
            ),
        ),
    ]
