# Generated by Django 4.2 on 2024-04-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_alter_passager_client_alter_reservation_numeroresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="numeroResa",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
